// Pick-lists the apps use. The list definitions live here; each workspace keeps its own values in
// its `lookups` table (seeded from `values` below), so it can relabel, recolor and reorder them.
//   kind "system": the code relies on these values; they can be relabeled, never added or removed
//   kind "custom": the workspace can add values and switch off the ones that came with PropFlow
// Records store only the value; labels and colors always come from the workspace's list.
// defaultable: the workspace picks one value that forms preselect (defaultValue to start with).
// Used by the tenant seed too, so no path aliases here.

export const LOOKUP_LISTS = [
  {
    key: "designation",
    name: "Designations",
    app: "users",
    kind: "custom",
    defaultable: true,
    description: "Job titles shown on user profiles and team pages.",
    values: [
      ["ceo", "Chief Executive"],
      ["manager", "Manager"],
      ["team-lead", "Team Lead"],
      ["sales-executive", "Sales Executive"],
      ["accounts-officer", "Accounts Officer"],
      ["admin-officer", "Admin Officer"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "department",
    name: "Departments",
    app: "users",
    kind: "custom",
    defaultable: true,
    description: "Departments people belong to.",
    values: [
      ["management", "Management"],
      ["sales", "Sales & Marketing"],
      ["accounts", "Accounts & Finance"],
      ["admin", "Admin & HR"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "member-status",
    name: "Member statuses",
    app: "users",
    kind: "system",
    colored: true,
    description: "Whether someone can sign in to this workspace, or hasn't accepted their invitation yet.",
    values: [
      { value: "active", label: "Active", color: "green" },
      { value: "suspended", label: "Suspended", color: "red" },
      { value: "invited", label: "Invited", color: "amber" },
    ],
  },
  // ---------- Project Portfolio ----------
  {
    key: "project-type",
    name: "Project types",
    app: "portfolio",
    kind: "custom",
    defaultable: true,
    defaultValue: "housing",
    icons: true,
    description: "What a project is: a housing society, apartments, a mall…",
    values: [
      { value: "housing", label: "Housing society", icon: "community-line" },
      { value: "apartments", label: "Apartments", icon: "building-line" },
      { value: "commercial", label: "Commercial", icon: "store-2-line" },
      { value: "farmhouses", label: "Farmhouses", icon: "home-8-line" },
      { value: "mixed", label: "Mixed use", icon: "building-2-line" },
    ],
  },
  {
    key: "project-status",
    name: "Project statuses",
    app: "portfolio",
    kind: "system",
    defaultable: true,
    defaultValue: "pre-launch",
    colored: true,
    description: "Where a project or phase is, from pre-launch to completion.",
    values: [
      { value: "pre-launch", label: "Pre-launch", color: "sky" },
      { value: "launched", label: "Launched", color: "blue" },
      { value: "under-development", label: "Under development", color: "amber" },
      { value: "under-construction", label: "Under construction", color: "amber" },
      { value: "possession", label: "Possession", color: "teal" },
      { value: "completed", label: "Completed", color: "green" },
    ],
  },
  {
    key: "approval-status",
    name: "Approval statuses",
    app: "portfolio",
    kind: "system",
    defaultable: true,
    defaultValue: "noc-applied",
    colored: true,
    icons: true,
    description: "Whether the approving authority has approved the project.",
    values: [
      { value: "approved", label: "Approved", color: "green", icon: "shield-check-line" },
      { value: "noc-applied", label: "NOC applied", color: "amber", icon: "time-line" },
      { value: "not-approved", label: "Not approved", color: "red", icon: "shield-cross-line" },
    ],
  },
  {
    key: "authority",
    name: "Approving authorities",
    app: "portfolio",
    kind: "custom",
    defaultable: true,
    defaultValue: "LDA",
    description: "Development authorities that approve projects. The value is the short name shown on badges.",
    values: [
      ["LDA", "Lahore Development Authority"],
      ["CDA", "Capital Development Authority"],
      ["RDA", "Rawalpindi Development Authority"],
      ["DHA", "Defence Housing Authority"],
      ["FDA", "Faisalabad Development Authority"],
      ["MDA", "Multan Development Authority"],
      ["SBCA", "Sindh Building Control Authority"],
      ["PHATA", "Punjab Housing & Town Planning Agency"],
      ["TMA", "Tehsil Municipal Administration"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "phase-stage",
    name: "Phase stages",
    app: "portfolio",
    kind: "system",
    defaultable: true,
    defaultValue: "balloted",
    description: "Balloted phases have numbered plots in blocks; unballoted phases hold open files until balloting.",
    values: [
      { value: "balloted", label: "Balloted (plots numbered)" },
      { value: "unballoted", label: "Unballoted (open files)" },
    ],
  },
  {
    key: "block-category",
    name: "Block categories",
    app: "portfolio",
    kind: "custom",
    defaultable: true,
    defaultValue: "residential",
    fields: [
      {
        key: "holds",
        label: "Holds",
        type: "select",
        options: [
          { value: "residential", label: "Residential units" },
          { value: "commercial", label: "Commercial units" },
          { value: "both", label: "Both" },
        ],
      },
    ],
    description: "Kinds of block, e.g. residential, commercial or mixed use. Holds decides which unit types a block can have.",
    values: [
      { value: "residential", label: "Residential", meta: { holds: "residential" } },
      { value: "commercial", label: "Commercial", meta: { holds: "commercial" } },
    ],
  },

  {
    key: "unit-type",
    name: "Unit types",
    app: "portfolio",
    kind: "custom",
    icons: true,
    fields: [
      { key: "plural", label: "Plural", type: "text", maxLength: 30 },
      {
        key: "measures",
        label: "Sized by",
        type: "select",
        options: [
          { value: "land", label: "Land (marla…)" },
          { value: "floor", label: "Floor area (sq ft…)" },
        ],
      },
      {
        key: "fits",
        label: "Fits",
        type: "select",
        options: [
          { value: "both", label: "Any block" },
          { value: "residential", label: "Residential blocks" },
          { value: "commercial", label: "Commercial blocks" },
          { value: "files", label: "Unballoted files" },
        ],
      },
    ],
    description: "Kinds of inventory. Sized by decides the units (marla, kanal… or sq ft, sq yd…); Fits decides which blocks can hold them.",
    values: [
      { value: "plot", label: "Plot", icon: "layout-grid-line", meta: { plural: "Plots", measures: "land", fits: "both" } },
      { value: "file", label: "File", icon: "file-paper-2-line", meta: { plural: "Files", measures: "land", fits: "files" } },
      { value: "house", label: "House", icon: "home-4-line", meta: { plural: "Houses", measures: "land", fits: "residential" } },
      { value: "apartment", label: "Apartment", icon: "building-line", meta: { plural: "Apartments", measures: "floor", fits: "residential" } },
      { value: "shop", label: "Shop", icon: "store-2-line", meta: { plural: "Shops", measures: "floor", fits: "commercial" } },
      { value: "office", label: "Office", icon: "briefcase-4-line", meta: { plural: "Offices", measures: "floor", fits: "commercial" } },
      { value: "farmhouse", label: "Farmhouse", icon: "home-8-line", meta: { plural: "Farmhouses", measures: "land", fits: "residential" } },
    ],
  },

  {
    key: "unit-status",
    name: "Unit statuses",
    app: "portfolio",
    kind: "system",
    colored: true,
    description: "Where a unit is in its sale. The order is also the order of the availability bars.",
    values: [
      { value: "available", label: "Available", color: "green" },
      { value: "on-hold", label: "On hold", color: "amber" },
      { value: "booked", label: "Booked", color: "blue" },
      { value: "sold", label: "Sold", color: "gray" },
      { value: "blocked", label: "Blocked", color: "red" },
    ],
  },
  {
    key: "feature",
    name: "Premium features",
    app: "portfolio",
    kind: "custom",
    fields: [{ key: "premium", label: "Premium %", type: "number", min: 0, max: 100 }],
    description: "Location features that add a premium to a unit's price, e.g. corner +10%.",
    values: [
      { value: "corner", label: "Corner", meta: { premium: 10 } },
      { value: "park-facing", label: "Park facing", meta: { premium: 10 } },
      { value: "main-boulevard", label: "Main boulevard", meta: { premium: 15 } },
      { value: "west-open", label: "West open", meta: { premium: 5 } },
      { value: "front-facing", label: "Front facing", meta: { premium: 20 } },
    ],
  },
  {
    key: "project-document-type",
    name: "Project document types",
    app: "portfolio",
    kind: "custom",
    defaultable: true,
    defaultValue: "other",
    icons: true,
    description: "Kinds of documents kept on a project: plans, approvals, brochures.",
    values: [
      { value: "layout-plan", label: "Layout / master plan", icon: "map-2-line" },
      { value: "noc", label: "NOC / approval letter", icon: "shield-check-line" },
      { value: "site-plan", label: "Site plan", icon: "road-map-line" },
      { value: "brochure", label: "Brochure", icon: "book-open-line" },
      { value: "payment-plan", label: "Payment plan", icon: "calendar-check-line" },
      { value: "legal", label: "Legal document", icon: "scales-3-line" },
      { value: "other", label: "Other", icon: "file-text-line" },
    ],
  },
  {
    key: "development-work",
    name: "Development works",
    app: "portfolio",
    kind: "custom",
    icons: true,
    description: "Work items whose progress is tracked on projects, e.g. roads 80%.",
    values: [
      { value: "roads", label: "Roads & streets", icon: "road-map-line" },
      { value: "electricity", label: "Electricity", icon: "flashlight-line" },
      { value: "sewerage", label: "Sewerage & drainage", icon: "drop-line" },
      { value: "water", label: "Water supply", icon: "water-flash-line" },
      { value: "gas", label: "Sui gas", icon: "fire-line" },
      { value: "boundary-wall", label: "Boundary wall & gates", icon: "shield-line" },
      { value: "parks", label: "Parks & landscaping", icon: "plant-line" },
      { value: "structure", label: "Building structure", icon: "building-4-line" },
      { value: "finishing", label: "Finishing", icon: "paint-brush-line" },
    ],
  },
  {
    key: "update-type",
    name: "Update types",
    app: "portfolio",
    kind: "custom",
    colored: true,
    defaultable: true,
    defaultValue: "construction",
    description: "Kinds of posts on a project's updates timeline.",
    values: [
      { value: "construction", label: "Construction progress", color: "#f59e0b" },
      { value: "announcement", label: "Announcement", color: "#3b82f6" },
      { value: "approval", label: "Approval", color: "#10b981" },
      { value: "balloting", label: "Balloting", color: "#8b5cf6" },
      { value: "possession", label: "Possession", color: "#14b8a6" },
    ],
  },
  {
    key: "event-type",
    name: "Event types",
    app: "portfolio",
    kind: "custom",
    icons: true,
    defaultable: true,
    defaultValue: "site-visit",
    description: "Kinds of project events: launches, balloting draws, ceremonies, expos.",
    values: [
      { value: "launch", label: "Launch", icon: "rocket-2-line" },
      { value: "balloting", label: "Balloting draw", icon: "dice-line" },
      { value: "possession", label: "Possession ceremony", icon: "key-2-line" },
      { value: "expo", label: "Property expo", icon: "store-3-line" },
      { value: "site-visit", label: "Site visit", icon: "map-pin-user-line" },
      { value: "groundbreaking", label: "Groundbreaking", icon: "hammer-line" },
    ],
  },
  {
    key: "hold-reason",
    name: "Hold reasons",
    app: "portfolio",
    kind: "custom",
    defaultable: true,
    defaultValue: "token",
    description: "Why a unit is put on hold for a while.",
    values: [
      { value: "token", label: "Token received, awaiting down payment" },
      { value: "site-visit", label: "Customer site visit" },
      { value: "dealer", label: "Dealer request" },
      { value: "management", label: "Management reserve" },
    ],
  },
  {
    key: "marla-size",
    name: "Marla sizes",
    app: "portfolio",
    kind: "custom",
    defaultable: true,
    defaultValue: "225",
    description: "Square feet in one marla. LDA, DHA and most private societies use 225; CDA and revenue records use 272.25.",
    values: [
      { value: "225", label: "225 sq ft (LDA, DHA, private societies)" },
      { value: "272.25", label: "272.25 sq ft (CDA, revenue)" },
    ],
  },
  {
    key: "area-unit",
    name: "Area units",
    app: "general",
    kind: "custom",
    fields: [
      { key: "short", label: "Short form", type: "text", maxLength: 12 },
      {
        key: "measures",
        label: "Measures",
        type: "select",
        options: [
          { value: "land", label: "Land (marla)" },
          { value: "floor", label: "Floor area (sq ft)" },
        ],
      },
      { key: "size", label: "Size", type: "number", min: 0.0001, max: 1000000, default: 1 },
    ],
    description:
      "Units sizes are measured in. Land units (plots, houses, files) are counted in marla, so they follow each project's marla size: Size is how many marla one unit is. Floor-area units (apartments, shops, offices) are counted in sq ft: Size is how many sq ft one unit is.",
    values: [
      { value: "marla", label: "Marla", meta: { short: "Marla", measures: "land", size: 1 } },
      { value: "kanal", label: "Kanal", meta: { short: "Kanal", measures: "land", size: 20 } },
      { value: "acre", label: "Acre", meta: { short: "Acre", measures: "land", size: 160 } },
      { value: "sqft", label: "Square feet", meta: { short: "sq ft", measures: "floor", size: 1 } },
      { value: "sqyd", label: "Square yards", meta: { short: "sq yd", measures: "floor", size: 9 } },
      { value: "sqm", label: "Square meters", meta: { short: "m²", measures: "floor", size: 10.7639 } },
    ],
  },

  // ---------- CRM ----------
  {
    key: "lead-status",
    name: "Lead statuses",
    app: "crm",
    kind: "system",
    colored: true,
    description: "Steps a lead moves through. New → Contacted → Interested → Site visit → Negotiation, then Booked or Lost.",
    values: [
      { value: "new", label: "New", color: "blue", meta: { stage: "open" } },
      { value: "contacted", label: "Contacted", color: "sky", meta: { stage: "open" } },
      { value: "interested", label: "Interested", color: "teal", meta: { stage: "open" } },
      { value: "site-visit", label: "Site visit scheduled", color: "amber", meta: { stage: "open" } },
      { value: "negotiation", label: "Negotiation", color: "violet", meta: { stage: "open" } },
      { value: "booked", label: "Booked", color: "green", meta: { stage: "won" } },
      { value: "lost", label: "Lost", color: "red", meta: { stage: "lost" } },
    ],
  },
  {
    key: "lead-priority",
    name: "Lead temperature",
    app: "crm",
    kind: "system",
    colored: true,
    icons: true,
    defaultable: true,
    defaultValue: "moderate",
    description: "How likely a lead is to book, from very cold to very hot.",
    values: [
      { value: "very-cold", label: "Very cold", color: "#2563eb", icon: "snowflake-line" },
      { value: "cold", label: "Cold", color: "#0ea5e9", icon: "temp-cold-line" },
      { value: "moderate", label: "Moderate", color: "#f59e0b", icon: "sun-cloudy-line" },
      { value: "hot", label: "Hot", color: "#f97316", icon: "fire-line" },
      { value: "very-hot", label: "Very hot", color: "#dc2626", icon: "fire-fill" },
    ],
  },
  {
    key: "lead-source",
    name: "Lead sources",
    app: "crm",
    kind: "custom",
    defaultable: true,
    defaultValue: "walk-in",
    description: "Where leads come from.",
    values: [
      ["property-portal", "Property portal"],
      ["facebook-ads", "Facebook ads"],
      ["instagram", "Instagram"],
      ["google-ads", "Google ads"],
      ["walk-in", "Walk-in"],
      ["site-office", "Site office visit"],
      ["dealer", "Dealer referral"],
      ["customer-referral", "Customer referral"],
      ["expo", "Property expo"],
      ["sms", "SMS campaign"],
      ["phone", "Phone call"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "contact-type",
    name: "Contact types",
    app: "general",
    kind: "custom",
    colored: true,
    icons: true,
    description: "What a contact is to your business. One contact can be several at once (a lead who books becomes a customer too); each comes from the records they're linked to.",
    values: [
      { value: "lead", label: "Lead", color: "blue", icon: "user-star-line" },
      { value: "customer", label: "Customer", color: "green", icon: "user-follow-line" },
      { value: "owner", label: "Owner / seller", color: "violet", icon: "home-4-line" },
      { value: "tenant", label: "Tenant", color: "teal", icon: "key-2-line" },
      { value: "dealer", label: "Dealer", color: "amber", icon: "shake-hands-line" },
      { value: "agent", label: "Agent", color: "sky", icon: "user-shared-line" },
      { value: "employee", label: "Employee", color: "gray", icon: "id-card-line" },
      { value: "vendor", label: "Vendor", color: "red", icon: "truck-line" },
      { value: "contractor", label: "Contractor", color: "red", icon: "hammer-line" },
    ],
  },
  {
    key: "booking-stage",
    name: "Booking pipeline",
    app: "operations",
    kind: "system",
    colored: true,
    description: "Steps a booking moves through, from token to completion. A token booking starts at Token; a full booking at Booking & KYC.",
    values: [
      { value: "token", label: "Token", color: "amber" },
      { value: "booking-kyc", label: "Booking & KYC", color: "sky" },
      { value: "active", label: "Active", color: "blue" },
      { value: "handover", label: "Handover", color: "violet" },
      { value: "completed", label: "Completed", color: "green" },
    ],
  },
  {
    key: "booking-status",
    name: "Booking statuses",
    app: "operations",
    kind: "custom",
    colored: true,
    defaultable: true,
    defaultValue: "current",
    description: "The standing of a booking, apart from its pipeline stage: e.g. a booking can be Active but Overdue or On hold.",
    values: [
      { value: "current", label: "Current", color: "green" },
      { value: "overdue", label: "Overdue", color: "amber" },
      { value: "defaulter", label: "Defaulter", color: "red" },
      { value: "on-hold", label: "On hold", color: "gray" },
      { value: "transferred", label: "Transferred", color: "violet" },
      { value: "cancelled", label: "Canceled", color: "red" },
      { value: "refunded", label: "Refunded", color: "teal" },
    ],
  },
  {
    key: "booking-document",
    name: "Booking documents",
    app: "operations",
    kind: "custom",
    icons: true,
    fields: [
      {
        key: "gate",
        label: "Needed before",
        type: "select",
        options: [
          { value: "allotment", label: "Allotment letter" },
          { value: "handover", label: "Handover" },
          { value: "possession", label: "Possession" },
          { value: "", label: "Not tied to a step" },
        ],
      },
      {
        key: "required",
        label: "Required?",
        type: "select",
        options: [
          { value: "yes", label: "Required" },
          { value: "no", label: "Optional" },
        ],
      },
    ],
    description: "The papers a booking collects on the way to handover. Required ones have to be uploaded before the step they're needed for (Operations › Customize › Settings can switch the check off).",
    values: [
      { value: "buyer-cnic", label: "Buyer's CNIC (both sides)", icon: "id-card-line", meta: { gate: "allotment", required: "yes" } },
      { value: "photos", label: "Passport-size photos", icon: "image-line", meta: { gate: "allotment", required: "yes" } },
      { value: "booking-form", label: "Signed booking form", icon: "file-text-line", meta: { gate: "allotment", required: "yes" } },
      { value: "nominee-cnic", label: "Nominee's CNIC", icon: "id-card-line", meta: { gate: "allotment", required: "no" } },
      { value: "signed-allotment", label: "Signed allotment letter", icon: "file-paper-2-line", meta: { gate: "handover", required: "yes" } },
      { value: "ndc", label: "No demand certificate (NDC)", icon: "shield-check-line", meta: { gate: "handover", required: "yes" } },
      { value: "possession-letter", label: "Signed possession letter", icon: "key-2-line", meta: { gate: "possession", required: "yes" } },
      { value: "other", label: "Other", icon: "file-line", meta: { gate: "", required: "no" } },
    ],
  },
  {
    key: "payment-method",
    name: "Payment methods",
    app: "operations",
    kind: "custom",
    icons: true,
    description: "How buyers pay. Cheques and pay orders wait in clearing until marked cleared.",
    values: [
      { value: "bank-transfer", label: "Bank transfer (IBFT)", icon: "bank-line" },
      { value: "cheque", label: "Cheque", icon: "bank-card-2-line" },
      { value: "pay-order", label: "Pay order", icon: "file-paper-2-line" },
      { value: "cash", label: "Cash", icon: "money-dollar-circle-line" },
      { value: "jazzcash", label: "JazzCash", icon: "smartphone-line" },
      { value: "easypaisa", label: "Easypaisa", icon: "smartphone-line" },
    ],
  },
  {
    key: "loss-reason",
    name: "Loss reasons",
    app: "crm",
    kind: "custom",
    description: "Why a lead didn't book.",
    values: [
      ["budget", "Over budget"],
      ["location", "Location not suitable"],
      ["competitor", "Bought elsewhere"],
      ["payment-plan", "Payment plan not suitable"],
      ["not-reachable", "Not reachable"],
      ["just-browsing", "Just browsing"],
      ["noc", "Concerned about approval / NOC"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "activity-type",
    name: "Activity types",
    app: "crm",
    // Workspaces add their own (e.g. Video call) and switch off what they don't use. Call,
    // WhatsApp and Site visit carry extra behavior (header shortcuts, Site visit stage).
    kind: "custom",
    icons: true,
    colored: true,
    // Score points: how much one of these (when they were reached) adds to a lead's engagement
    fields: [{ key: "points", label: "Score points", type: "number", min: 0, max: 50 }],
    description: "What can be logged or planned against a lead: calls, messages, visits. Add your own or switch off what you don't use. Score points count towards a lead's engagement.",
    values: [
      { value: "call", label: "Call", icon: "phone-line", color: "blue", meta: { points: 3 } },
      { value: "whatsapp", label: "WhatsApp", icon: "whatsapp-line", color: "green", meta: { points: 2 } },
      { value: "site-visit", label: "Site visit", icon: "map-pin-user-line", color: "amber", meta: { points: 10 } },
      { value: "meeting", label: "Office meeting", icon: "team-line", color: "violet", meta: { points: 8 } },
      { value: "email", label: "Email", icon: "mail-line", color: "sky", meta: { points: 1 } },
      { value: "sms", label: "SMS", icon: "message-2-line", color: "teal", meta: { points: 1 } },
    ],
  },
  {
    key: "activity-outcome",
    name: "Activity outcomes",
    app: "crm",
    kind: "custom",
    icons: true,
    colored: true,
    fields: [
      {
        key: "moves",
        label: "Moves the lead to",
        type: "select",
        options: [
          { value: "", label: "Doesn't move it" },
          { value: "contacted", label: "Contacted" },
          { value: "interested", label: "Interested" },
          { value: "site-visit", label: "Site visit scheduled" },
          { value: "negotiation", label: "Negotiation" },
        ],
      },
      {
        key: "reached",
        label: "Reached them?",
        type: "select",
        options: [
          { value: "yes", label: "Yes, we spoke" },
          { value: "no", label: "No (no answer, switched off…)" },
        ],
      },
      {
        key: "signal",
        label: "Effect on lead score",
        type: "select",
        options: [
          { value: "positive", label: "Positive" },
          { value: "neutral", label: "Neutral" },
          { value: "negative", label: "Negative" },
        ],
      },
    ],
    description: "How a call, message or visit went. Each can move the lead forward (never back), says whether you reached them, and can raise or lower the lead's score.",
    values: [
      { value: "interested", label: "Interested", icon: "thumb-up-line", color: "green", meta: { moves: "interested", reached: "yes", signal: "positive" } },
      { value: "call-back", label: "Call back", icon: "time-line", color: "sky", meta: { moves: "contacted", reached: "yes", signal: "neutral" } },
      { value: "no-answer", label: "No answer", icon: "phone-off-line", color: "amber", meta: { moves: "", reached: "no", signal: "neutral" } },
      { value: "not-interested", label: "Not interested", icon: "thumb-down-line", color: "red", meta: { moves: "contacted", reached: "yes", signal: "negative" } },
    ],
  },
  {
    key: "follow-up",
    name: "Follow-up options",
    app: "crm",
    kind: "custom",
    icons: true,
    colored: true,
    defaultable: true,
    defaultValue: "tomorrow",
    fields: [{ key: "days", label: "Days later", type: "number", min: 0, max: 365 }],
    description: "When to follow up after logging a call or visit. Each is that many days later, at 11 AM.",
    values: [
      { value: "tomorrow", label: "Tomorrow", icon: "calendar-event-line", color: "blue", meta: { days: 1 } },
      { value: "3-days", label: "In 3 days", icon: "calendar-2-line", color: "sky", meta: { days: 3 } },
      { value: "next-week", label: "Next week", icon: "calendar-line", color: "violet", meta: { days: 7 } },
      { value: "two-weeks", label: "In 2 weeks", icon: "calendar-schedule-line", color: "teal", meta: { days: 14 } },
      { value: "next-month", label: "Next month", icon: "calendar-todo-line", color: "amber", meta: { days: 30 } },
    ],
  },
  {
    key: "quick-reply",
    name: "Quick replies",
    app: "crm",
    kind: "custom",
    icons: true,
    fields: [{ key: "text", label: "Text", type: "longtext", maxLength: 500 }],
    description: "Ready-made notes and message text: tap one when logging a call or writing an email to add its text.",
    values: [
      { value: "brochure-sent", label: "Brochure sent", icon: "file-pdf-2-line", meta: { text: "Shared the brochure, price list and payment plan on WhatsApp." } },
      { value: "wants-visit", label: "Wants a site visit", icon: "map-pin-user-line", meta: { text: "Interested in visiting the site. Will confirm a day and time." } },
      { value: "checking-budget", label: "Checking budget", icon: "wallet-3-line", meta: { text: "Discussing the budget with family; will get back after going through the payment plan." } },
      { value: "busy", label: "Busy, call later", icon: "time-line", meta: { text: "Was busy; asked us to call back later." } },
      { value: "best-price", label: "Asked for best price", icon: "price-tag-3-line", meta: { text: "Asked for the best price and any discount on cash payment." } },
      { value: "documents", label: "Asked about documents", icon: "file-shield-2-line", meta: { text: "Asked about NOC / approval and ownership documents." } },
    ],
  },
  // ---------- General ----------
  {
    key: "city",
    name: "Cities",
    app: "general",
    kind: "custom",
    // Records store the city's name itself, so new values keep their name as the value
    valueIsLabel: true,
    defaultable: true,
    defaultValue: "Lahore",
    description: "Cities used across the workspace: projects, dealers, contacts.",
    values: ["Lahore", "Karachi", "Islamabad", "Rawalpindi", "Faisalabad", "Multan", "Peshawar", "Gujranwala", "Sialkot", "Hyderabad", "Quetta", "Bahawalpur"].map((c) => ({ value: c, label: c })),
  },
  {
    key: "campaign-status",
    name: "Campaign statuses",
    app: "campaigns",
    kind: "system",
    description: "Where a campaign is in its life. Reports rely on these, so they can be renamed and recolored but not removed.",
    colored: true,
    values: [
      { value: "draft", label: "Draft", color: "gray" },
      { value: "scheduled", label: "Scheduled", color: "sky" },
      { value: "active", label: "Live", color: "green" },
      { value: "paused", label: "Paused", color: "amber" },
      { value: "completed", label: "Ended", color: "violet" },
    ],
  },
  {
    key: "campaign-objective",
    name: "Campaign objectives",
    app: "campaigns",
    kind: "custom",
    description: "What a campaign is for. Used to group campaigns in lists and reports.",
    icons: true,
    values: [
      { value: "launch", label: "Project launch", icon: "rocket-2-line" },
      { value: "pre-launch", label: "Pre-launch registrations", icon: "file-list-3-line" },
      { value: "balloting", label: "Balloting / draw", icon: "shuffle-line" },
      { value: "booking-drive", label: "Booking drive", icon: "hand-coin-line" },
      { value: "event", label: "Expo / event", icon: "calendar-event-line" },
      { value: "overseas", label: "Overseas roadshow", icon: "plane-line" },
      { value: "possession", label: "Possession / handover", icon: "key-2-line" },
      { value: "resale", label: "Resale & rentals", icon: "home-4-line" },
      { value: "always-on", label: "Always-on", icon: "infinity-line" },
      { value: "awareness", label: "Brand awareness", icon: "megaphone-line" },
    ],
  },
  {
    key: "service-request-type",
    name: "Request types",
    app: "estate",
    kind: "system",
    description: "What a buyer or resident can ask for. The app relies on these; rename and recolor them only.",
    colored: true,
    icons: true,
    values: [
      { value: "transfer", label: "Transfer", color: "violet", icon: "arrow-left-right-line" },
      { value: "ndc", label: "NDC", color: "teal", icon: "shield-check-line" },
      { value: "possession", label: "Possession", color: "green", icon: "key-2-line" },
      { value: "complaint", label: "Complaint", color: "amber", icon: "error-warning-line" },
      { value: "document", label: "Document", color: "sky", icon: "file-copy-2-line" },
      { value: "record-update", label: "Record update", color: "gray", icon: "edit-box-line" },
    ],
  },
  {
    key: "service-status",
    name: "Request statuses",
    app: "estate",
    kind: "system",
    description: "Where a request is. The app relies on these; rename and recolor them only.",
    colored: true,
    values: [
      { value: "new", label: "New", color: "blue" },
      { value: "in-progress", label: "In progress", color: "amber" },
      { value: "awaiting-customer", label: "Waiting on customer", color: "violet" },
      { value: "completed", label: "Done", color: "green" },
      { value: "rejected", label: "Rejected", color: "gray" },
    ],
  },
  {
    key: "service-priority",
    name: "Complaint priorities",
    app: "estate",
    kind: "system",
    description: "How urgent a complaint is; each has its own response time (Customize › Fees & timelines).",
    colored: true,
    values: [
      { value: "urgent", label: "Urgent", color: "red" },
      { value: "high", label: "High", color: "amber" },
      { value: "normal", label: "Normal", color: "blue" },
      { value: "low", label: "Low", color: "gray" },
    ],
  },
  {
    key: "complaint-category",
    name: "Complaint categories",
    app: "estate",
    kind: "custom",
    description: "What residents complain about. Used to sort complaints and in reports.",
    icons: true,
    values: [
      { value: "water-supply", label: "Water supply", icon: "drop-line" },
      { value: "sewerage", label: "Sewerage", icon: "contrast-drop-2-line" },
      { value: "electricity", label: "Electricity", icon: "flashlight-line" },
      { value: "streetlights", label: "Streetlights", icon: "lightbulb-line" },
      { value: "security", label: "Security", icon: "shield-user-line" },
      { value: "cleanliness", label: "Cleanliness", icon: "delete-bin-2-line" },
      { value: "lift", label: "Lift", icon: "arrow-up-down-line" },
      { value: "parks", label: "Parks", icon: "plant-line" },
      { value: "gas", label: "Gas", icon: "fire-line" },
      { value: "roads", label: "Roads", icon: "road-map-line" },
      { value: "other", label: "Other", icon: "question-line" },
    ],
  },
  {
    key: "service-document",
    name: "Documents on request",
    app: "estate",
    kind: "custom",
    description: "Documents buyers can ask for; each has its own fee (Customize › Fees & timelines).",
    values: [
      { value: "duplicate-allotment", label: "Duplicate allotment letter" },
      { value: "statement", label: "Statement of account" },
      { value: "site-plan", label: "Site plan" },
      { value: "noc-mortgage", label: "NOC for mortgage" },
    ],
  },
  {
    key: "service-channel",
    name: "Request channels",
    app: "estate",
    kind: "custom",
    description: "How a request came in.",
    values: [
      { value: "walk-in", label: "Walk-in" },
      { value: "phone", label: "Phone" },
      { value: "whatsapp", label: "WhatsApp" },
      { value: "email", label: "Email" },
      { value: "letter", label: "Letter" },
    ],
  },
  {
    key: "vendor-category",
    name: "Vendor categories",
    app: "finance",
    kind: "custom",
    icons: true,
    description: "What a vendor supplies, for grouping payments.",
    values: [
      { value: "contractor", label: "Contractor", icon: "hammer-line" },
      { value: "supplier", label: "Material supplier", icon: "truck-line" },
      { value: "media", label: "Media & advertising", icon: "megaphone-line" },
      { value: "utility", label: "Utility", icon: "flashlight-line" },
      { value: "professional", label: "Professional services", icon: "briefcase-4-line" },
      { value: "landlord", label: "Landlord", icon: "home-4-line" },
      { value: "government", label: "Government & authority", icon: "government-line" },
      { value: "other", label: "Other", icon: "more-line" },
    ],
  },
]

export const lookupList = (key) => LOOKUP_LISTS.find((l) => l.key === key) ?? null

// Color names older values may hold (new colors are hex from the color picker)
export const LOOKUP_COLORS = ["gray", "blue", "sky", "teal", "green", "amber", "red", "violet"]

// Headings for lists grouped by app in the editor
export const LOOKUP_APPS = { users: "Users & Teams", portfolio: "Project Portfolio", campaigns: "Campaigns", crm: "CRM", operations: "Operations", estate: "Estate Management", finance: "Finance", general: "General" }

// "Senior Sales Executive" → senior-sales-executive
export const slugify = (text) =>
  String(text)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50)
