// Pick-lists the apps use. The list definitions live here; each workspace keeps its own values in
// its `lookups` table (seeded from `values` below), so it can relabel, recolour and reorder them.
//   kind "system": the code relies on these values; they can be relabelled, never added or removed
//   kind "custom": the workspace can add values and switch off the ones that came with PropFlow
// Records store only the value; labels and colours always come from the workspace's list.
// defaultable: the workspace picks one value that forms preselect (defaultValue to start with).
// Used by the tenant seed too, so no path aliases here.

export const LOOKUP_LISTS = [
  {
    key: "designation",
    name: "Designations",
    app: "users",
    kind: "custom",
    defaultable: true,
    description: "Job titles shown on user profiles and team pages.",
    values: [
      ["ceo", "Chief Executive"],
      ["manager", "Manager"],
      ["team-lead", "Team Lead"],
      ["sales-executive", "Sales Executive"],
      ["accounts-officer", "Accounts Officer"],
      ["admin-officer", "Admin Officer"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "department",
    name: "Departments",
    app: "users",
    kind: "custom",
    defaultable: true,
    description: "Departments people belong to.",
    values: [
      ["management", "Management"],
      ["sales", "Sales & Marketing"],
      ["accounts", "Accounts & Finance"],
      ["admin", "Admin & HR"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "member-status",
    name: "Member statuses",
    app: "users",
    kind: "system",
    colored: true,
    description: "Whether someone can sign in to this workspace, or hasn't accepted their invitation yet.",
    values: [
      { value: "active", label: "Active", color: "green" },
      { value: "suspended", label: "Suspended", color: "red" },
      { value: "invited", label: "Invited", color: "amber" },
    ],
  },
  // ---------- Estate Management ----------
  {
    key: "project-type",
    name: "Project types",
    app: "estate",
    kind: "custom",
    defaultable: true,
    defaultValue: "housing",
    icons: true,
    description: "What a project is: a housing society, apartments, a mall…",
    values: [
      { value: "housing", label: "Housing society", icon: "community-line" },
      { value: "apartments", label: "Apartments", icon: "building-line" },
      { value: "commercial", label: "Commercial", icon: "store-2-line" },
      { value: "farmhouses", label: "Farmhouses", icon: "home-8-line" },
      { value: "mixed", label: "Mixed use", icon: "building-2-line" },
    ],
  },
  {
    key: "project-status",
    name: "Project statuses",
    app: "estate",
    kind: "system",
    defaultable: true,
    defaultValue: "pre-launch",
    colored: true,
    description: "Where a project or phase is, from pre-launch to completion.",
    values: [
      { value: "pre-launch", label: "Pre-launch", color: "sky" },
      { value: "launched", label: "Launched", color: "blue" },
      { value: "under-development", label: "Under development", color: "amber" },
      { value: "under-construction", label: "Under construction", color: "amber" },
      { value: "possession", label: "Possession", color: "teal" },
      { value: "completed", label: "Completed", color: "green" },
    ],
  },
  {
    key: "approval-status",
    name: "Approval statuses",
    app: "estate",
    kind: "system",
    defaultable: true,
    defaultValue: "noc-applied",
    colored: true,
    icons: true,
    description: "Whether the approving authority has approved the project.",
    values: [
      { value: "approved", label: "Approved", color: "green", icon: "shield-check-line" },
      { value: "noc-applied", label: "NOC applied", color: "amber", icon: "time-line" },
      { value: "not-approved", label: "Not approved", color: "red", icon: "shield-cross-line" },
    ],
  },
  {
    key: "authority",
    name: "Approving authorities",
    app: "estate",
    kind: "custom",
    defaultable: true,
    defaultValue: "LDA",
    description: "Development authorities that approve projects. The value is the short name shown on badges.",
    values: [
      ["LDA", "Lahore Development Authority"],
      ["CDA", "Capital Development Authority"],
      ["RDA", "Rawalpindi Development Authority"],
      ["DHA", "Defence Housing Authority"],
      ["FDA", "Faisalabad Development Authority"],
      ["MDA", "Multan Development Authority"],
      ["SBCA", "Sindh Building Control Authority"],
      ["PHATA", "Punjab Housing & Town Planning Agency"],
      ["TMA", "Tehsil Municipal Administration"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "phase-stage",
    name: "Phase stages",
    app: "estate",
    kind: "system",
    defaultable: true,
    defaultValue: "balloted",
    description: "Balloted phases have numbered plots in blocks; unballoted phases hold open files until balloting.",
    values: [
      { value: "balloted", label: "Balloted (plots numbered)" },
      { value: "unballoted", label: "Unballoted (open files)" },
    ],
  },
  {
    key: "block-category",
    name: "Block categories",
    app: "estate",
    kind: "custom",
    defaultable: true,
    defaultValue: "residential",
    fields: [
      {
        key: "holds",
        label: "Holds",
        type: "select",
        options: [
          { value: "residential", label: "Residential units" },
          { value: "commercial", label: "Commercial units" },
          { value: "both", label: "Both" },
        ],
      },
    ],
    description: "Kinds of block, e.g. residential, commercial or mixed use. Holds decides which unit types a block can have.",
    values: [
      { value: "residential", label: "Residential", meta: { holds: "residential" } },
      { value: "commercial", label: "Commercial", meta: { holds: "commercial" } },
    ],
  },

  {
    key: "unit-type",
    name: "Unit types",
    app: "estate",
    kind: "custom",
    icons: true,
    fields: [
      { key: "plural", label: "Plural", type: "text", maxLength: 30 },
      {
        key: "measures",
        label: "Sized by",
        type: "select",
        options: [
          { value: "land", label: "Land (marla…)" },
          { value: "floor", label: "Floor area (sq ft…)" },
        ],
      },
      {
        key: "fits",
        label: "Fits",
        type: "select",
        options: [
          { value: "both", label: "Any block" },
          { value: "residential", label: "Residential blocks" },
          { value: "commercial", label: "Commercial blocks" },
          { value: "files", label: "Unballoted files" },
        ],
      },
    ],
    description: "Kinds of inventory. Sized by decides the units (marla, kanal… or sq ft, sq yd…); Fits decides which blocks can hold them.",
    values: [
      { value: "plot", label: "Plot", icon: "layout-grid-line", meta: { plural: "Plots", measures: "land", fits: "both" } },
      { value: "file", label: "File", icon: "file-paper-2-line", meta: { plural: "Files", measures: "land", fits: "files" } },
      { value: "house", label: "House", icon: "home-4-line", meta: { plural: "Houses", measures: "land", fits: "residential" } },
      { value: "apartment", label: "Apartment", icon: "building-line", meta: { plural: "Apartments", measures: "floor", fits: "residential" } },
      { value: "shop", label: "Shop", icon: "store-2-line", meta: { plural: "Shops", measures: "floor", fits: "commercial" } },
      { value: "office", label: "Office", icon: "briefcase-4-line", meta: { plural: "Offices", measures: "floor", fits: "commercial" } },
      { value: "farmhouse", label: "Farmhouse", icon: "home-8-line", meta: { plural: "Farmhouses", measures: "land", fits: "residential" } },
    ],
  },

  {
    key: "unit-status",
    name: "Unit statuses",
    app: "estate",
    kind: "system",
    colored: true,
    description: "Where a unit is in its sale. The order is also the order of the availability bars.",
    values: [
      { value: "available", label: "Available", color: "green" },
      { value: "on-hold", label: "On hold", color: "amber" },
      { value: "booked", label: "Booked", color: "blue" },
      { value: "sold", label: "Sold", color: "gray" },
      { value: "blocked", label: "Blocked", color: "red" },
    ],
  },
  {
    key: "feature",
    name: "Premium features",
    app: "estate",
    kind: "custom",
    fields: [{ key: "premium", label: "Premium %", type: "number", min: 0, max: 100 }],
    description: "Location features that add a premium to a unit's price, e.g. corner +10%.",
    values: [
      { value: "corner", label: "Corner", meta: { premium: 10 } },
      { value: "park-facing", label: "Park facing", meta: { premium: 10 } },
      { value: "main-boulevard", label: "Main boulevard", meta: { premium: 15 } },
      { value: "west-open", label: "West open", meta: { premium: 5 } },
      { value: "front-facing", label: "Front facing", meta: { premium: 20 } },
    ],
  },
  {
    key: "project-document-type",
    name: "Project document types",
    app: "estate",
    kind: "custom",
    defaultable: true,
    defaultValue: "other",
    icons: true,
    description: "Kinds of documents kept on a project: plans, approvals, brochures.",
    values: [
      { value: "layout-plan", label: "Layout / master plan", icon: "map-2-line" },
      { value: "noc", label: "NOC / approval letter", icon: "shield-check-line" },
      { value: "site-plan", label: "Site plan", icon: "road-map-line" },
      { value: "brochure", label: "Brochure", icon: "book-open-line" },
      { value: "payment-plan", label: "Payment plan", icon: "calendar-check-line" },
      { value: "legal", label: "Legal document", icon: "scales-3-line" },
      { value: "other", label: "Other", icon: "file-text-line" },
    ],
  },
  {
    key: "development-work",
    name: "Development works",
    app: "estate",
    kind: "custom",
    icons: true,
    description: "Work items whose progress is tracked on projects, e.g. roads 80%.",
    values: [
      { value: "roads", label: "Roads & streets", icon: "road-map-line" },
      { value: "electricity", label: "Electricity", icon: "flashlight-line" },
      { value: "sewerage", label: "Sewerage & drainage", icon: "drop-line" },
      { value: "water", label: "Water supply", icon: "water-flash-line" },
      { value: "gas", label: "Sui gas", icon: "fire-line" },
      { value: "boundary-wall", label: "Boundary wall & gates", icon: "shield-line" },
      { value: "parks", label: "Parks & landscaping", icon: "plant-line" },
      { value: "structure", label: "Building structure", icon: "building-4-line" },
      { value: "finishing", label: "Finishing", icon: "paint-brush-line" },
    ],
  },
  {
    key: "update-type",
    name: "Update types",
    app: "estate",
    kind: "custom",
    colored: true,
    defaultable: true,
    defaultValue: "construction",
    description: "Kinds of posts on a project's updates timeline.",
    values: [
      { value: "construction", label: "Construction progress", color: "#f59e0b" },
      { value: "announcement", label: "Announcement", color: "#3b82f6" },
      { value: "approval", label: "Approval", color: "#10b981" },
      { value: "balloting", label: "Balloting", color: "#8b5cf6" },
      { value: "possession", label: "Possession", color: "#14b8a6" },
    ],
  },
  {
    key: "event-type",
    name: "Event types",
    app: "estate",
    kind: "custom",
    icons: true,
    defaultable: true,
    defaultValue: "site-visit",
    description: "Kinds of project events: launches, balloting draws, ceremonies, expos.",
    values: [
      { value: "launch", label: "Launch", icon: "rocket-2-line" },
      { value: "balloting", label: "Balloting draw", icon: "dice-line" },
      { value: "possession", label: "Possession ceremony", icon: "key-2-line" },
      { value: "expo", label: "Property expo", icon: "store-3-line" },
      { value: "site-visit", label: "Site visit", icon: "map-pin-user-line" },
      { value: "groundbreaking", label: "Groundbreaking", icon: "hammer-line" },
    ],
  },
  {
    key: "hold-reason",
    name: "Hold reasons",
    app: "estate",
    kind: "custom",
    defaultable: true,
    defaultValue: "token",
    description: "Why a unit is put on hold for a while.",
    values: [
      { value: "token", label: "Token received, awaiting down payment" },
      { value: "site-visit", label: "Customer site visit" },
      { value: "dealer", label: "Dealer request" },
      { value: "management", label: "Management reserve" },
    ],
  },
  {
    key: "marla-size",
    name: "Marla sizes",
    app: "estate",
    kind: "custom",
    defaultable: true,
    defaultValue: "225",
    description: "Square feet in one marla. LDA, DHA and most private societies use 225; CDA and revenue records use 272.25.",
    values: [
      { value: "225", label: "225 sq ft (LDA, DHA, private societies)" },
      { value: "272.25", label: "272.25 sq ft (CDA, revenue)" },
    ],
  },
  {
    key: "area-unit",
    name: "Area units",
    app: "general",
    kind: "custom",
    fields: [
      { key: "short", label: "Short form", type: "text", maxLength: 12 },
      {
        key: "measures",
        label: "Measures",
        type: "select",
        options: [
          { value: "land", label: "Land (marla)" },
          { value: "floor", label: "Floor area (sq ft)" },
        ],
      },
      { key: "size", label: "Size", type: "number", min: 0.0001, max: 1000000, default: 1 },
    ],
    description: "Units sizes are measured in. Land units (plots, houses, files) are counted in marla, so they follow each project's marla size: Size is how many marla one unit is. Floor-area units (apartments, shops, offices) are counted in sq ft: Size is how many sq ft one unit is.",
    values: [
      { value: "marla", label: "Marla", meta: { short: "Marla", measures: "land", size: 1 } },
      { value: "kanal", label: "Kanal", meta: { short: "Kanal", measures: "land", size: 20 } },
      { value: "acre", label: "Acre", meta: { short: "Acre", measures: "land", size: 160 } },
      { value: "sqft", label: "Square feet", meta: { short: "sq ft", measures: "floor", size: 1 } },
      { value: "sqyd", label: "Square yards", meta: { short: "sq yd", measures: "floor", size: 9 } },
      { value: "sqm", label: "Square metres", meta: { short: "m²", measures: "floor", size: 10.7639 } },
    ],
  },

  // ---------- CRM ----------
  {
    key: "lead-status",
    name: "Lead statuses",
    app: "crm",
    kind: "system",
    colored: true,
    description: "Steps a lead moves through. New → Contacted → Interested → Site visit → Negotiation, then Booked or Lost.",
    values: [
      { value: "new", label: "New", color: "blue", meta: { stage: "open" } },
      { value: "contacted", label: "Contacted", color: "sky", meta: { stage: "open" } },
      { value: "interested", label: "Interested", color: "teal", meta: { stage: "open" } },
      { value: "site-visit", label: "Site visit scheduled", color: "amber", meta: { stage: "open" } },
      { value: "negotiation", label: "Negotiation", color: "violet", meta: { stage: "open" } },
      { value: "booked", label: "Booked", color: "green", meta: { stage: "won" } },
      { value: "lost", label: "Lost", color: "red", meta: { stage: "lost" } },
    ],
  },
  {
    key: "lead-priority",
    name: "Lead temperature",
    app: "crm",
    kind: "system",
    colored: true,
    icons: true,
    defaultable: true,
    defaultValue: "moderate",
    description: "How likely a lead is to book, from very cold to very hot.",
    values: [
      { value: "very-cold", label: "Very cold", color: "#2563eb", icon: "snowflake-line" },
      { value: "cold", label: "Cold", color: "#0ea5e9", icon: "temp-cold-line" },
      { value: "moderate", label: "Moderate", color: "#f59e0b", icon: "sun-cloudy-line" },
      { value: "hot", label: "Hot", color: "#f97316", icon: "fire-line" },
      { value: "very-hot", label: "Very hot", color: "#dc2626", icon: "fire-fill" },
    ],
  },
  {
    key: "lead-source",
    name: "Lead sources",
    app: "crm",
    kind: "custom",
    defaultable: true,
    defaultValue: "walk-in",
    description: "Where leads come from.",
    values: [
      ["property-portal", "Property portal"],
      ["facebook-ads", "Facebook ads"],
      ["instagram", "Instagram"],
      ["google-ads", "Google ads"],
      ["walk-in", "Walk-in"],
      ["site-office", "Site office visit"],
      ["dealer", "Dealer referral"],
      ["customer-referral", "Customer referral"],
      ["expo", "Property expo"],
      ["sms", "SMS campaign"],
      ["phone", "Phone call"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "loss-reason",
    name: "Loss reasons",
    app: "crm",
    kind: "custom",
    description: "Why a lead didn't book.",
    values: [
      ["budget", "Over budget"],
      ["location", "Location not suitable"],
      ["competitor", "Bought elsewhere"],
      ["payment-plan", "Payment plan not suitable"],
      ["not-reachable", "Not reachable"],
      ["just-browsing", "Just browsing"],
      ["noc", "Concerned about approval / NOC"],
    ].map(([value, label]) => ({ value, label })),
  },
  {
    key: "activity-type",
    name: "Activity types",
    app: "crm",
    kind: "system",
    icons: true,
    description: "Kinds of follow-up logged against leads.",
    values: [
      { value: "call", label: "Call", icon: "phone-line" },
      { value: "whatsapp", label: "WhatsApp", icon: "whatsapp-line" },
      { value: "site-visit", label: "Site visit", icon: "map-pin-user-line" },
      { value: "meeting", label: "Office meeting", icon: "team-line" },
      { value: "email", label: "Email", icon: "mail-line" },
      { value: "sms", label: "SMS", icon: "message-2-line" },
    ],
  },
  // ---------- General ----------
  {
    key: "city",
    name: "Cities",
    app: "general",
    kind: "custom",
    // Records store the city's name itself, so new values keep their name as the value
    valueIsLabel: true,
    defaultable: true,
    defaultValue: "Lahore",
    description: "Cities used across the workspace: projects, dealers, contacts.",
    values: ["Lahore", "Karachi", "Islamabad", "Rawalpindi", "Faisalabad", "Multan", "Peshawar", "Gujranwala", "Sialkot", "Hyderabad", "Quetta", "Bahawalpur"].map((c) => ({ value: c, label: c })),
  },
]

export const lookupList = (key) => LOOKUP_LISTS.find((l) => l.key === key) ?? null

// Colour names older values may hold (new colours are hex from the colour picker)
export const LOOKUP_COLORS = ["gray", "blue", "sky", "teal", "green", "amber", "red", "violet"]

// Headings for lists grouped by app in the editor
export const LOOKUP_APPS = { users: "Users & Teams", estate: "Estate Management", crm: "CRM", general: "General" }

// "Senior Sales Executive" → senior-sales-executive
export const slugify = (text) =>
  String(text)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50)
